linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - ireturn
    - testpackage
    - varnamelen

issues:
  exclude-use-default: false
  exclude-rules:
    - path: example_test\.go
      linters:
        - lll
