name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Test build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./... -bench=. -coverprofile=coverage.txt -covermode=atomic
